In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
np.random.randint(1,100,(3,5))

array([[50, 56, 88, 56, 14],
       [53, 17, 40, 90, 18],
       [49, 49, 43, 26, 95]])

In [17]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size = (2,2), replace = False)

array([[2.6, 1.5],
       [4.9, 1. ]])

In [18]:
np.random.normal(size=(1,3))

array([[-0.31703423,  0.27136036,  0.75130607]])

In [25]:
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
x = np.arange(36).reshape(3,4,3)
temp = x.ravel()
print(temp)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [37]:
x[0,0,0]=100
temp

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35])

In [55]:
x = [-1,1,2,3]
map(lambda x:x+1,x)

In [42]:
filter?

Init signature: filter(self, /, *args, **kwargs)
Docstring:     
filter(function or None, iterable) --> filter object

Return an iterator yielding those items of iterable for which function(item)
is true. If function is None, return the items that are true.
Type:           type
Subclasses:     


In [43]:
map?

Init signature: map(self, /, *args, **kwargs)
Docstring:     
map(func, *iterables) --> map object

Make an iterator that computes the function using arguments from
each of the iterables.  Stops when the shortest iterable is exhausted.
Type:           type
Subclasses:     
