## 학습목표
 1. linalg 서브모듈 함수 활용여 선형대수 연산하기

In [2]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [6]:
x = np.random.rand(3, 3)
print(x)

np.matmul(x,np.linalg.inv(x))

[[0.53837691 0.56016895 0.38451076]
 [0.1389757  0.40157005 0.33651521]
 [0.15057506 0.76614272 0.09613087]]


array([[ 1.00000000e+00,  8.02523193e-17,  3.06744777e-17],
       [ 2.10746576e-17,  1.00000000e+00, -4.44098993e-17],
       [-5.88859928e-17,  6.14697712e-17,  1.00000000e+00]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [11]:
A = np.array([[1, 1],[2, 4]])
B = np.array([25, 64])
ans = np.linalg.solve(A,B)

In [12]:
np.allclose(np.matmul(A,ans),B)

True