## 학습목표
 1. 브로드캐스팅의 이해

In [1]:
import numpy as np

#### 브로드캐스팅
  - Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    


#### 브로드캐스팅 Rule
 - [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

* Shape이 같은 경우의 연산

In [3]:
x = np.arange(15).reshape(3, 5)
y = np.random.randn(15).reshape(3,5)
print(x)
print(y)
x*y

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0.31923952  1.29765823  0.55100244  0.58565175 -0.63802031]
 [-0.37897409 -0.18898626  0.04626404 -2.77628049 -0.82741353]
 [-0.06534695 -1.0945176  -0.80528537  0.75386905  0.21579975]]


array([[  0.        ,   1.29765823,   1.10200488,   1.75695526,
         -2.55208124],
       [ -1.89487043,  -1.13391753,   0.32384825, -22.21024389,
         -7.44672181],
       [ -0.65346951, -12.03969357,  -9.66342443,   9.80029768,
          3.02119644]])

* Scalar(상수)와의 연산

In [10]:
print(x + 2)
x % 2 == 0

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]


array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

* Shape이 다른 경우 연산

In [26]:
a = np.arange(12).reshape(4,3)
b = np.arange(100, 103)
c = np.arange(1000,1004)
d = np.arange(6).reshape(2,3)

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

(4, 3)
(3,)
(4,)
(2, 3)
